FROM mcr.microsoft.com/dotnet-buildtools/prereqs:azurelinux-3.0-net9.0-cross-arm64-musl
COPY --from=mcr.microsoft.com/dotnet/sdk:9.0.304-azurelinux3.0-amd64 /usr/share/dotnet /usr/share/dotnet
RUN if [ -e /usr/bin/dotnet ]; then rm /usr/bin/dotnet; fi
RUN ln -s /usr/share/dotnet/dotnet /usr/bin/dotnet
ENV DOTNET_NOLOGO=true
